package com.anthonyzero.seed.modules.user.mapper;

import com.anthonyzero.seed.modules.user.domain.SmUserToken;
import com.anthonyzero.seed.modules.user.domain.SmUserTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    long countByExample(SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int deleteByExample(SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int insert(SmUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int insertSelective(SmUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmUserToken selectOneByExample(SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    List<SmUserToken> selectByExample(SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    SmUserToken selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") SmUserToken record, @Param("example") SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int updateByExample(@Param("record") SmUserToken record, @Param("example") SmUserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int updateByPrimaryKeySelective(SmUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated Thu Jul 12 11:26:55 CST 2018
     */
    int updateByPrimaryKey(SmUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SmUserToken> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_token
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SmUserToken> list, @Param("selective") SmUserToken.Column ... selective);
}