package com.anthonyzero.seed.modules.sys.domain;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sm_user
 */
public class SmUser {

	/**
	 * Database Column Remarks: 用户ID This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.user_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 用户名称 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.user_name
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String userName;
	/**
	 * Database Column Remarks: 登录账号 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.user_code
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String userCode;
	/**
	 * Database Column Remarks: 用户密码 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.password
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String password;
	/**
	 * Database Column Remarks: 部门ID This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.depart_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private Long departId;
	/**
	 * Database Column Remarks: 盐 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.salt
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String salt;
	/**
	 * Database Column Remarks: 头像图片 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.avatar
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String avatar;
	/**
	 * Database Column Remarks: 用户类型 1系统用户 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.user_type
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private Integer userType;
	/**
	 * Database Column Remarks: 邮箱 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.email
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String email;
	/**
	 * Database Column Remarks: 手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.mobile
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.user_desc
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private String userDesc;
	/**
	 * Database Column Remarks: 状态 0 无效1 正常 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.state
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private Integer state;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column sm_user.create_time
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.user_id
	 * @return  the value of sm_user.user_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.user_id
	 * @param userId  the value for sm_user.user_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.user_name
	 * @return  the value of sm_user.user_name
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.user_name
	 * @param userName  the value for sm_user.user_name
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.user_code
	 * @return  the value of sm_user.user_code
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.user_code
	 * @param userCode  the value for sm_user.user_code
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode == null ? null : userCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.password
	 * @return  the value of sm_user.password
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.password
	 * @param password  the value for sm_user.password
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.depart_id
	 * @return  the value of sm_user.depart_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public Long getDepartId() {
		return departId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.depart_id
	 * @param departId  the value for sm_user.depart_id
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setDepartId(Long departId) {
		this.departId = departId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.salt
	 * @return  the value of sm_user.salt
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.salt
	 * @param salt  the value for sm_user.salt
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.avatar
	 * @return  the value of sm_user.avatar
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.avatar
	 * @param avatar  the value for sm_user.avatar
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.user_type
	 * @return  the value of sm_user.user_type
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.user_type
	 * @param userType  the value for sm_user.user_type
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.email
	 * @return  the value of sm_user.email
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.email
	 * @param email  the value for sm_user.email
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.mobile
	 * @return  the value of sm_user.mobile
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.mobile
	 * @param mobile  the value for sm_user.mobile
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.user_desc
	 * @return  the value of sm_user.user_desc
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public String getUserDesc() {
		return userDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.user_desc
	 * @param userDesc  the value for sm_user.user_desc
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setUserDesc(String userDesc) {
		this.userDesc = userDesc == null ? null : userDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.state
	 * @return  the value of sm_user.state
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.state
	 * @param state  the value for sm_user.state
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_user.create_time
	 * @return  the value of sm_user.create_time
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_user.create_time
	 * @param createTime  the value for sm_user.create_time
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This enum was generated by MyBatis Generator. This enum corresponds to the database table sm_user
	 * @mbg.generated
	 * @project  https://github.com/itfsw/mybatis-generator-plugin
	 */
	public enum Column {
		userId("user_id", "userId", "BIGINT", false), userName("user_name", "userName", "VARCHAR", false), userCode("user_code", "userCode", "VARCHAR", false), password("password", "password",
				"VARCHAR", false), departId("depart_id", "departId", "BIGINT", false), salt("salt", "salt", "VARCHAR", false), avatar("avatar", "avatar", "VARCHAR", false), userType("user_type",
						"userType", "INTEGER", false), email("email", "email", "VARCHAR", false), mobile("mobile", "mobile", "VARCHAR",
								false), userDesc("user_desc", "userDesc", "VARCHAR", false), state("state", "state", "INTEGER", false), createTime("create_time", "createTime", "TIMESTAMP", false);
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private static final String BEGINNING_DELIMITER = "\"";
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private static final String ENDING_DELIMITER = "\"";
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private final String column;
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private final boolean isColumnNameDelimited;
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private final String javaProperty;
		/**
		* This field was generated by MyBatis Generator. This field corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		private final String jdbcType;

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String value() {
			return this.column;
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String getValue() {
			return this.column;
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public static Column[] excludes(Column... excludes) {
			ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new Column[] {});
		}

		/**
		* This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
		* @mbg.generated
		* @project  https://github.com/itfsw/mybatis-generator-plugin
		*/
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
			} else {
				return this.column;
			}
		}
	}
}