# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8860
    context-path: /seed

# spring
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化d
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            maxFileSize: 100MB
            maxRequestSize: 1000MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
swagger.enable: true