package com.anthonyzero.seed.modules.sys.mapper;

import com.anthonyzero.seed.modules.sys.domain.SmFile;
import com.anthonyzero.seed.modules.sys.domain.SmFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    long countByExample(SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int deleteByExample(SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int deleteByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int insert(SmFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int insertSelective(SmFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SmFile selectOneByExample(SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    List<SmFile> selectByExample(SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    SmFile selectByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") SmFile record, @Param("example") SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int updateByExample(@Param("record") SmFile record, @Param("example") SmFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int updateByPrimaryKeySelective(SmFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated Thu Jul 12 11:28:08 CST 2018
     */
    int updateByPrimaryKey(SmFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SmFile> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SmFile> list, @Param("selective") SmFile.Column ... selective);
}