package com.anthonyzero.seed.modules.sys.mapper;

import com.anthonyzero.seed.modules.sys.domain.SmUser;
import com.anthonyzero.seed.modules.sys.domain.SmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmUserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	long countByExample(SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int deleteByExample(SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int insert(SmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int insertSelective(SmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated
	 * @project  https://github.com/itfsw/mybatis-generator-plugin
	 */
	SmUser selectOneByExample(SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	List<SmUser> selectByExample(SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	SmUser selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SmUser record, @Param("example") SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int updateByExample(@Param("record") SmUser record, @Param("example") SmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int updateByPrimaryKeySelective(SmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated  Wed Jul 11 11:24:20 CST 2018
	 */
	int updateByPrimaryKey(SmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated
	 * @project  https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsert(@Param("list") List<SmUser> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_user
	 * @mbg.generated
	 * @project  https://github.com/itfsw/mybatis-generator-plugin
	 */
	int batchInsertSelective(@Param("list") List<SmUser> list, @Param("selective") SmUser.Column... selective);

	void updateState(Long userId);
}